### ISSUE TITLE
Allow comparison between a "network property" and an "arithmetic binary operator"

### ISSUE THREAD

**Issue by pgambier** [itesla/ipst-core#97]
The following function cannot work because it is not possible to compare a "network property" and an "arithmetic binary operator".
```
def isOverloaded(lineIds, abattement) {
lineIds.collect({lineId -> line(lineId).terminal1.i > line(lineId).currentLimits1.permanentLimit*abattement})
		.inject({a, b -> a.or2(b)})
}
```
The Abstract Syntax Tree should be fixed to allow this kind of comparison.

**Comment by mathbagu** [comment]
This error is thrown by the [compareToWithEqualityCheck method](https://github.com/groovy/groovy-core/blob/master/src/main/org/codehaus/groovy/runtime/typehandling/DefaultTypeTransformation.java) because ExpressionNode interface does not extend the Comparable<ExpressionNode> interface.

Proposal workaround:
```
def isOverloaded(lineIds, reduction) {
    lineIds.collect({lineId -> line(lineId).terminal1.i.compareTo2(line(lineId).currentLimits1.permanentLimit*reduction, ">") })
            .inject({a, b -> a.or2(b)})
}
```
